
services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=serviceDesk
      - POSTGRES_USER=unico
      - POSTGRES_PASSWORD=1234
    ports:
      - 5440:5440
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80